export const iconsData = [
    { name: "FaHome", category: "classic free solid regular", type: "free",},
    { name: "FaHourglass", category: "classic free solid regular", type: "free", },
    { name: "FaUserAlt", category: "classic free solid regular", type: "free", },
    { name: "FaVideo", category: "classic free solid regular", type: "free",},
    { name: "FaEnvelope", category: "classic sharp free solid regular", type: "free",},
    { name: "FaCamera", category: "classic free solid regular", type: "free",},
    { name: "FaMusic", category: "classic pro  light solid regular light thin duotone", type: "pro", },
    { name: "FaFilm", category: "classic sharp pro solid regular light thin duotone", type: "pro",},
    { name: "FaShoppingCart", category: "classic pro solid regular light thin duotone", type: "pro",},
    { name: "FaCar", category: "classic sharp pro solid regular light thin duotone", type: "pro", },
    { name: "FaStar", category: "classic pro  solid regular light thin duotone", type: "pro", },
    { name: "FaHeart", category: "classic pro solid regular light thin duotone", type: "pro", },
    { name: "FaGamepad", category: "classic free solid regular sharp", type: "free", },
    { name: "FaGlobe", category: "classic sharp free solid regular", type: "free",  },
    { name: "FaSun", category: "classic sharp free solid regular", type: "free",  },
    { name: "FaMoon", category: "classic free solid regular", type: "free",  },
    { name: "FaBook", category: "classic free solid regular", type: "free", },
    { name: "FaBriefcase", category: "classic pro solid regular light thin duotone", type: "pro", },
    { name: "FaCoffee", category: "classic free solid regular", type: "free",  },
    { name: "FaCode", category: "classic free solid regular", type: "free", },
    { name: "FaFacebookF", category: "classic sharp brands free regular", type: "free",  },
    { name: "FaLinkedinIn", category: "classic sharp brands free regular", type: "free", },
    { name: "FaGoogle", category: "classic brands free", type: "free", },
    { name: "FaInstagram", category: "classic brands pro regular light thin duotone", type: "pro", },
    { name: "FaAirbnb", category: "classic brands pro regular light thin duotone", type: "pro", },
];