export const iconsData = [
    { name: "FaHome", category: "classic free", type: "free", style:"solid regular" },
    { name: "FaHourglass", category: "classic free", type: "free", style:"solid regular" },
    { name: "FaUserAlt", category: "classic free", type: "free", style:"solid regular" },
    { name: "FaVideo", category: "classic free", type: "free", style:"solid regular" },
    { name: "FaEnvelope", category: "classic sharp free", type: "free", style:"solid regular" },
    { name: "FaCamera", category: "classic free", type: "free", style:"solid regular" },
    { name: "FaMusic", category: "classic pro", type: "pro", style:"solid regular light thin duotone" },
    { name: "FaFilm", category: "classic sharp pro", type: "pro", style:"solid regular light thin duotone" },
    { name: "FaShoppingCart", category: "classic pro", type: "pro", style:"solid regular light thin duotone" },
    { name: "FaCar", category: "classic sharp pro", type: "pro", style:"solid regular light thin duotone" },
    { name: "FaStar", category: "classic pro", type: "pro", style:"solid regular light thin duotone" },
    { name: "FaHeart", category: "classic pro", type: "pro", style:"solid regular light thin duotone" },
    { name: "FaGamepad", category: "classic free sharp", type: "free", style:"solid regular" },
    { name: "FaGlobe", category: "classic sharp free", type: "free", style:"solid regular" },
    { name: "FaSun", category: "classic sharp free", type: "free", style:"solid regular" },
    { name: "FaMoon", category: "classic free", type: "free", style:"solid regular" },
    { name: "FaBook", category: "classic free", type: "free", style:"solid regular" },
    { name: "FaBriefcase", category: "classic pro", type: "pro", style:"solid regular light thin duotone" },
    { name: "FaCoffee", category: "classic free", type: "free", style:"solid regular" },
    { name: "FaCode", category: "classic free", type: "free", style:"solid regular" },
    { name: "FaFacebookF", category: "classic sharp brands free", type: "free", style:"regular" },
    { name: "FaLinkedinIn", category: "classic sharp brands free", type: "free", style:"regular" },
    { name: "FaGoogle", category: "classic brands free", type: "free", style:"regular" },
    { name: "FaInstagram", category: "classic brands pro", type: "pro", style:"regular light thin duotone" },
    { name: "FaAirbnb", category: "classic brands pro", type: "pro", style:"regular light thin duotone" },
];